CI: download newest OOSDK toolchain
bucanero/PS4CheatsManager pull request #104
Opened 2023-07-12 15:39 UTC by illusion0001

2023-07-12 15:43 UTC, bucanero requested changes

2023-07-12 15:43 UTC, bucanero commented on .github/workflows/build.yml
> +      run: curl -sL https://github.com/illusion0001/OpenOrbis-PS4-Toolchain/releases/latest/download/toolchain.tar.gz | tar xz -C ./
Shouldn't we just update the URL on `env.OO_SDK_URL` ?

(or remove the OO_SDK_URL env variable)

2023-07-12 15:46 UTC, illusion0001 commented on .github/workflows/build.yml
> +      run: curl -sL https://github.com/illusion0001/OpenOrbis-PS4-Toolchain/releases/latest/download/toolchain.tar.gz | tar xz -C ./
It was only used for caching key, it does not make a difference in terms of download speed in my testing so I just removed it. Roughly 2-3 seconds to download and extract it using cache and without

2023-07-12 17:05 UTC, bucanero approved these changes

2023-07-12 17:09 UTC, bucanero commented
I think we should do a quick test and confirm if the generated `.pkg` works as expected, to avoid problems showing up later  due to the updated SDK

2023-07-18 22:24 UTC, illusion0001 commented
tested, app still works same as before

2023-07-18 22:25 UTC, merged